### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yechentide** [cqmoe/cqcppsdk-template#2]
环境: MacOS 10.14.6(Mojave) / CLion 2019.3

错误信息: 

```
/Users/....../extern/cqcppsdk/src/core/dir.cpp:14:18: error: 'exists' is unavailable: introduced in macOS 10.15
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:1617:39: note: 'exists' has been explicitly marked unavailable here

/Users/....../extern/cqcppsdk/src/core/dir.cpp:14:25: error: 'path' is unavailable: introduced in macOS 10.15
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:773:3: note: 'path' has been explicitly marked unavailable here

/Users/....../extern/cqcppsdk/src/core/dir.cpp:15:24: error: 'create_directories' is unavailable: introduced in macOS 10.15
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:1548:39: note: 'create_directories' has been explicitly marked unavailable here

/Users/....../extern/cqcppsdk/src/core/dir.cpp:28:56: error: 'operator/' is unavailable: introduced in macOS 10.15
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:1175:41: note: 'operator/' has been explicitly marked unavailable here

...............
```

**Comment by yechentide** [comment]
这是叫我升级系统吗。。。Mojave下有办法build吗

**Comment by stdrc** [comment]
Mojave 上的 Clang 可能比较老（我只在 Catalina 的 Clang 11 上测试过），试试换 GCC 吧

**Comment by yechentide** [comment]
原来mac上的compiler是clang。。。我试试下载gcc

**Comment by yechentide** [comment]
不知道CLion改路径优先级。。所以我直接在终端build了，貌似还是用的clang
但是我没找到app.dll和app_dev，只有一个app_dev.dir文件夹里面一堆东西
下面是build信息：
❯ cmake ..
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cqcppsdk dir: /Users/....../template/extern/cqcppsdk
-- app id: com.example.demo
-- dev mode: ON
-- add dev mode executable: app_dev
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/....../template/build

**Comment by yechentide** [comment]
这次cmake用了GCC9.2
生成的文件感觉一模一样
❯ cmake -DCMAKE_CXX_COMPILER=/usr/local/bin/g++ ..
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/bin/g++
-- Check for working CXX compiler: /usr/local/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cqcppsdk dir: /Users/yechentide/downloads/CoolQ/template/extern/cqcppsdk
-- app id: com.example.demo
-- dev mode: ON
-- add dev mode executable: app_dev
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/yechentide/downloads/CoolQ/template/build

**Comment by yechentide** [comment]
不知道CLion怎么改路径优先级。。所以我直接在终端build了
先是用clang来cmake了一次，然后换成gcc9.2
两次生成的文件看上去一样
但是我没找到app.dll和app_dev，只有一个app_dev.dir文件夹里面一堆东西
下面是build信息：
```
❯ cmake -DCMAKE_CXX_COMPILER=/usr/local/bin/g++ -DCMAKE_C_COMPILER=/usr/local/bin/gcc ..

-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/bin/g++
-- Check for working CXX compiler: /usr/local/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cqcppsdk dir: /Users/....../template/extern/cqcppsdk
-- app id: com.example.demo
-- dev mode: ON
-- add dev mode executable: app_dev
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/....../template/build
```

**Comment by yechentide** [comment]
build
├── CMakeCache.txt
├── CMakeFiles
│   ├── 3.16.3
│   │   ├── CMakeCCompiler.cmake
│   │   ├── CMakeCXXCompiler.cmake
│   │   ├── CMakeDetermineCompilerABI_C.bin
│   │   ├── CMakeDetermineCompilerABI_CXX.bin
│   │   ├── CMakeSystem.cmake
│   │   ├── CompilerIdC
│   │   │   ├── CMakeCCompilerId.c
│   │   │   ├── a.out
│   │   │   └── tmp
│   │   └── CompilerIdCXX
│   │       ├── CMakeCXXCompilerId.cpp
│   │       ├── a.out
│   │       └── tmp
│   ├── CMakeDirectoryInformation.cmake
│   ├── CMakeOutput.log
│   ├── CMakeTmp
│   ├── Makefile.cmake
│   ├── Makefile2
│   ├── TargetDirectories.txt
│   ├── app_dev.dir
│   │   ├── DependInfo.cmake
│   │   ├── build.make
│   │   ├── cmake_clean.cmake
│   │   ├── depend.make
│   │   ├── extern
│   │   │   └── cqcppsdk
│   │   │       └── src
│   │   │           ├── core
│   │   │           ├── dev_mode
│   │   │           └── utils
│   │   │               └── vendor
│   │   │                   └── cpp-base64
│   │   ├── flags.make
│   │   ├── link.txt
│   │   ├── progress.make
│   │   └── src
│   ├── cmake.check_cache
│   └── progress.marks
├── Makefile
└── cmake_install.cmake

**Comment by yechentide** [comment]
自己解决了，方法为CLion更改了gcc和g++的路径
`Preferences -> Toolchains`里面，新建一个toolchain，修改gcc和g++路径。
因为我是用brew安装的，所以路径分别是
`/usr/local/bin/gcc`
`/usr/local/bin/g++`
修改后，把这个toolchain移到最上面一行（最上面的为启用）
然后点Apply就好了。
我重新复制了下模板试了一下，如果不行的话，
把default和自己新建的toolchain再切换一下就好了
